server:
  port: 8200

spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-auth
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:dev}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 31440414v
    url: jdbc:mysql://localhost:3306/session_user_db?useUnicode=true&characterEncoding=utf-8&8allowWMulti
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      test-on-borrow: true
      validation-query: SELECT 1
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML

    servlet:
      content-type: text/html
      # 启用布局方言
      layout:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #数据库下划线和驼峰映射

logging:
  level:
    com.order.feign: debug

jwt:
  secret: "7A2B4C6D8E0F1A3B5C7D9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1C2D3E4F5A6B7C8D9E0F1A2B3C4D5E6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B1567"
  expiration: 3600000 # 1小时